### ISSUE TITLE
Lots of non user-facing instance methods rendered in documentation

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty#101]
Due to recent changes by @falexwolf 

https://docs.lamin.ai/bionty.cellline#methods

I don't think that all of these instance methods are relevant for users

**Comment by falexwolf** [comment]
Yes, I'm aware and thinking through how to go about it. It holds for any `Record` subclass.

The thing is that these functions are part of the public API. We just didn't _show_ them, so the problem is only now visible on the docs, but existed before.

**Comment by falexwolf** [comment]
Hm, wait, maybe this is just because `django-private-api` is switched on when building the docs. That'd be a trivial fix.

**Comment by falexwolf** [comment]
Yes, this should fix it:

- https://github.com/laminlabs/lamin-docs/pull/134
