### ISSUE TITLE
Update Experimental Factor Ontology to 3.67+

### ISSUE THREAD

**Issue by andreassteffen** [laminlabs/bionty#124]
current bionty does not contain https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0022615

**Comment by Zethson** [comment]
Hi,

this is currently blocked by https://github.com/laminlabs/bionty/issues/65 and more specifically https://github.com/EBISPOT/efo/issues/2264. I'm happy that you want the Xenium EFO term because I got it added. We also need this for other projects so getting this resolved is of high priority.

I will try to fix this upstream.

**Comment by Zethson** [comment]
Dear @andreassteffen,

I've just updated our `bionty-assets` instance which hosts the optimized (and in this case fixed) version of the ontologies and added EFO 3.70.0.

You have to update your instance by running:

```
import bionty as bt

# Sync your instance with laminlabs/bionty-assets to get the latest ontology versions
bt.core.sync_all_sources_to_latest()

# Load the latest (in this case 3.70.0) ontology version
new_efo = bt.Source.filter(entity="bionty.ExperimentalFactor", version="3.70.0").one()
bt.ExperimentalFactor.import_from_source(new_efo)
```

then you can test it using

```
bt.ExperimentalFactor.search("xenium")
```

which should return

```
<QuerySet [ExperimentalFactor(uid='1nPAU7Yf', name='10x Xenium', ontology_id='EFO:0022615', synonyms='Xenium', description='Xenium Is A Spatial Profiling Technology From 10X Genomics That Utilizes High-Resolution Imaging To Simultaneously Analyze The Expression Of Hundreds Of Rna Targets Within A Single Tissue Section.', molecule='RNA assay', created_by_id=2, source_id=135, updated_at='2024-10-02 09:11:43 UTC')]>
```

I tested it with `pfizer/usecases` where the latest EFO version should now be available. Please let us know if you run into trouble. We are planning to have a UI button that makes the syncing of the ontology versions easier but for now it requires the few API calls.
