### ISSUE TITLE
Be more opinionated about mapping symbols vs ensembl IDs

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty#143]
https://laminlabs.slack.com/archives/C04MU979KD3/p1730749687519699

1. A warning when mapping against symbols
2. A link in the warning to a FAQ section where we explain why mapping against symbols is discouraged, how to convert symbols to ENSEMBL IDs, and finally why this is also not perfectly accurate.

**Comment by falexwolf** [comment]
> A warning when mapping against symbols

What's interesting about this warning is that we're currently not warning when people curate any other features against semantic names. I imagine we'd like similar warnings for protein identifiers and cell markers in the future, maybe even metadata features; but I don't have enough intuition yet.
