### ISSUE TITLE
Setting currently used bionty source does not exclude records with no source_id

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty#26]
Still investigating but something is fishy.

```python
human_110 = bt.Source.using("laminlabs/cellxgene").filter(version="release-110", organism="human").one()
human_110.set_as_currently_used()
```

requires a reload of the instance

```python
!lamin close
!lamin load test-cellxgene-curate
```

```python
curate = cxg.Curate(adata, organism="human")
# [...]
validated = curate.validate()  # passes
artifact = curate.save_artifact(description="test h5ad file")
```

Now when we eventually validate it using cellxgene-schema:
```bash
cellxgene-schema validate anndata_human_immune_cells_cxg.h5ad
```

We still get many genes that are not validated. I looked deeper into these genes and noticed that none of them have a source_id (why that is the case in the first place - different question - we don't know).

```python
ensembl_ids = [
    'ENSG00000269933', 'ENSG00000261737', 'ENSG00000259834', 'ENSG00000256374',
    'ENSG00000263464', 'ENSG00000203812', 'ENSG00000272196', 'ENSG00000272880',
    'ENSG00000270188', 'ENSG00000287116', 'ENSG00000237133', 'ENSG00000224739',
    'ENSG00000227902', 'ENSG00000239467', 'ENSG00000272551', 'ENSG00000280374',
    'ENSG00000236886', 'ENSG00000229352', 'ENSG00000286601', 'ENSG00000227021',
    'ENSG00000259855', 'ENSG00000273301', 'ENSG00000271870', 'ENSG00000237838',
    'ENSG00000286996', 'ENSG00000269028', 'ENSG00000286699', 'ENSG00000273370',
    'ENSG00000261490', 'ENSG00000272567', 'ENSG00000270394', 'ENSG00000272370',
    'ENSG00000272354', 'ENSG00000251044', 'ENSG00000272040', 'ENSG00000182230',
    'ENSG00000204092', 'ENSG00000261068', 'ENSG00000236740', 'ENSG00000236996',
    'ENSG00000232295', 'ENSG00000271734', 'ENSG00000236673', 'ENSG00000227220',
    'ENSG00000236166', 'ENSG00000112096', 'ENSG00000285162', 'ENSG00000286228',
    'ENSG00000237513', 'ENSG00000285106', 'ENSG00000226380', 'ENSG00000270672',
    'ENSG00000225932', 'ENSG00000244693', 'ENSG00000268955', 'ENSG00000272267',
    'ENSG00000253878', 'ENSG00000259820', 'ENSG00000226403', 'ENSG00000233776',
    'ENSG00000269900', 'ENSG00000261534', 'ENSG00000237548', 'ENSG00000239665',
    'ENSG00000256892', 'ENSG00000249860', 'ENSG00000271409', 'ENSG00000224745',
    'ENSG00000261438', 'ENSG00000231575', 'ENSG00000260461', 'ENSG00000255823',
    'ENSG00000254740', 'ENSG00000254561', 'ENSG00000282080', 'ENSG00000256427',
    'ENSG00000287388', 'ENSG00000276814', 'ENSG00000280710', 'ENSG00000215271',
    'ENSG00000258414', 'ENSG00000258808', 'ENSG00000277050', 'ENSG00000273888',
    'ENSG00000258861', 'ENSG00000259444', 'ENSG00000244952', 'ENSG00000273923',
    'ENSG00000262668', 'ENSG00000232196', 'ENSG00000256618', 'ENSG00000221995',
    'ENSG00000226377', 'ENSG00000273576', 'ENSG00000267637', 'ENSG00000282965',
    'ENSG00000273837', 'ENSG00000286949', 'ENSG00000256222', 'ENSG00000280095',
    'ENSG00000278927', 'ENSG00000278955', 'ENSG00000277352', 'ENSG00000239446',
    'ENSG00000256045', 'ENSG00000228906', 'ENSG00000228139', 'ENSG00000261773',
    'ENSG00000278198', 'ENSG00000273496', 'ENSG00000277666', 'ENSG00000278782',
    'ENSG00000277761'
]

bt.Gene.using("laminlabs/cellxgene").filter(ensembl_gene_id__in=ensembl_ids).df()
```

shows us that none of these have source_ids.

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>uid</th>
      <th>symbol</th>
      <th>stable_id</th>
      <th>ensembl_gene_id</th>
      <th>ncbi_gene_ids</th>
      <th>biotype</th>
      <th>synonyms</th>
      <th>description</th>
      <th>organism_id</th>
      <th>source_id</th>
      <th>run_id</th>
      <th>created_by_id</th>
      <th>updated_at</th>
    </tr>
    <tr>
      <th>id</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>173629</th>
      <td>3Eua9MMuSc7b</td>
      <td>SOD2</td>
      <td>None</td>
      <td>ENSG00000112096</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>8</td>
      <td>None</td>
      <td>None</td>
      <td>1</td>
      <td>2023-11-29 09:25:10.196078+00:00</td>
    </tr>
    <tr>
      <th>173615</th>
      <td>7HKWa8xrNwYQ</td>
      <td>FAM153B_ENSG00000182230</td>
      <td>None</td>
      <td>ENSG00000182230</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>8</td>
      <td>None</td>
      <td>None</td>
      <td>1</td>
      <td>2023-11-29 09:25:10.195744+00:00</td>
    </tr>
    <tr>
      <th>173579</th>
      <td>3E7aAO6yP5lZ</td>
      <td>H2AC18</td>
      <td>None</td>
      <td>ENSG00000203812</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>8</td>
      <td>None</td>
      <td>None</td>
      <td>1</td>
      <td>2023-11-29 09:25:10.194849+00:00</td>
    </tr>
    <tr>
      <th>173617</th>
      <td>6nEGIHFsMYgD</td>
      <td>LINC00951</td>
      <td>None</td>
      <td>ENSG00000204092</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>8</td>
      <td>None</td>
      <td>None</td>
      <td>1</td>
      <td>2023-11-29 09:25:10.195791+00:00</td>
    </tr>
    <tr>
      <th>173672</th>
      <td>3Xqm80mYkh5Y</td>
      <td>HOMEZ</td>
      <td>None</td>
      <td>ENSG00000215271</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>8</td>
      <td>None</td>
      <td>None</td>
      <td>1</td>
      <td>2023-11-29 09:25:10.197105+00:00</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>173603</th>
      <td>hjdnNPXLhPFz</td>
      <td>RP11-454H13.8</td>
      <td>None</td>
      <td>ENSG00000286699</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>8</td>
      <td>None</td>
      <td>None</td>
      <td>1</td>
      <td>2023-11-29 09:25:10.195433+00:00</td>
    </tr>
    <tr>
      <th>173697</th>
      <td>3s3LE6tF2au0</td>
      <td>CTD-2368P22.2</td>
      <td>None</td>
      <td>ENSG00000286949</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>8</td>
      <td>None</td>
      <td>None</td>
      <td>1</td>
      <td>2023-11-29 09:25:10.197696+00:00</td>
    </tr>
    <tr>
      <th>173601</th>
      <td>1z4W9aNyiZMB</td>
      <td>RP11-256B12.2</td>
      <td>None</td>
      <td>ENSG00000286996</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>8</td>
      <td>None</td>
      <td>None</td>
      <td>1</td>
      <td>2023-11-29 09:25:10.195385+00:00</td>
    </tr>
    <tr>
      <th>173584</th>
      <td>97kgVFoVNxPh</td>
      <td>RP11-433K2.9</td>
      <td>None</td>
      <td>ENSG00000287116</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>8</td>
      <td>None</td>
      <td>None</td>
      <td>1</td>
      <td>2023-11-29 09:25:10.194973+00:00</td>
    </tr>
    <tr>
      <th>173668</th>
      <td>4JYXi62EHtC3</td>
      <td>RP11-820K3.7</td>
      <td>None</td>
      <td>ENSG00000287388</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>8</td>
      <td>None</td>
      <td>None</td>
      <td>1</td>
      <td>2023-11-29 09:25:10.197009+00:00</td>
    </tr>
  </tbody>
</table>
<p>113 rows × 13 columns</p>
</div>

```python
bt.Source.using("laminlabs/cellxgene").filter(currently_used=True, entity="Gene").df()
```

confirms that release-110 is currently used for human.

Further validated by checking that

```python
release_110_only = bt.Gene.using("laminlabs/cellxgene").filter(source_id="8").df()  # 8 -> release-110
matching_ids = [ensembl_id for ensembl_id in ensembl_ids if ensembl_id in release_110_only["ensembl_gene_id"].values]

print(matching_ids)
```

returns an empty list

**Comment by falexwolf** [comment]
This also sounds like a somewhat un-intuitive behavior even though I get that our reference is the lamindb registry, not the ontology. So, I guess it makes sense. 🤔
