### ISSUE TITLE
displaying children of Cell Ontology term

### ISSUE THREAD

**Issue by indapa** [laminlabs/bionty#36]
Hi, 

I am new to lamin. I have some code that tries to display the ontology tree of Cell Ontology terms:

```
`!lamin init --storage ./Lamin/test-cell-type --schema bionty

import lnschema_bionty as lb
import pandas as pd

public = lb.CellType.public()

lookup = public.lookup()
lookup_dict = lookup.dict()

dch_cell = lb.CellType(lookup_dict["dendritic cell"])

dch_cell.view_parents( with_children=True)`
```

Does the view_parents function display any grand children of the cell ontology term? The reason I ask is CellXGene does a cell type [rollup] (https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_3__Gene%20Expression%20Data%20Processing) and I would like to display the ontology tree with bionty for all the cell type descendants of a cell type (not just the first one)

![image](https://github.com/laminlabs/bionty/assets/456750/5cf8ac8c-bf96-4c18-a1fd-ba1992669529)

**Comment by sunnyosun** [comment]
You can now use `CellType.import_from_source` to bulk add all records into LaminDB. If you do so, all parents and children will be populated.
