### ISSUE TITLE
🍱 2024-08: Update sources to latest

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty#58]
- [x] Source: cl has a more recent version: 2024-05-15
- [x] Source: doid has a more recent version: 2024-05-29
- [x] Source: dron has a more recent version: 2024-03-03
- [x] Source: efo has a more recent version: 3.67.0
- [x] Source: go has a more recent version: 2024-06-17
- [x] Source: hp has a more recent version: 2024-04-26
- [x] Source: mondo has a more recent version: 2024-06-04
- [x] Source: mp has a more recent version: 2024-06-18
- [ ] Source: ncbitaxon has a more recent version: 2024-05-08
- [x] Source: pato has a more recent version: 2024-03-28
- [x] Source: pw has a more recent version: 7.84
- [x] Source: uberon has a more recent version: 2024-05-13
- [x] Source: zp has a more recent version: 2024-04-18

**Comment by sunnyosun** [comment]
Can we have a set frequency for this type of update? I don't think we need every version of everything, and people can always make issues if they want a specific version.

I'd say we do such an update every quarter?

**Comment by Zethson** [comment]
> Can we have a set frequency for this type of update? I don't think we need every version of everything, and people can always make issues if they want a specific version.
> 
> I'd say we do such an update every quarter?

I needed some versions for cellxgene. Sure. At the moment I get a reminder every month. Every quarter is fine with me.

**Comment by Zethson** [comment]
By the way, the last update was 3-4 months ago ^_^

**Comment by sunnyosun** [comment]
But the cellxgene ones are more of older versions, I'm more saying to "update to latest".

**Comment by Zethson** [comment]
I know, I added the old ones and now I am adding the most recent ones and then we're good for several months.
