### ISSUE TITLE
Update readme and show coverage

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/bionty#74]
For the new readme, shall we follow the style of lamindb?

The readme on lamindb is so minimal to avoid code duplications that are inevitable if using features like dropdowns that simply don't work in GitHub markdown.

I think the old readme was great as a standalone, but today I'd say everything should be centralized on docs.lamin.ai/bionty

<img width="904" alt="image" src="https://github.com/user-attachments/assets/22dcad97-64e9-4826-8690-70177d2dfec8">

**Comment by sunnyosun** [comment]
Are you suggesting to remove this?

**Comment by falexwolf** [comment]
Yes, I'm suggesting to have the readme consistent with lamindb's readme with just a few bullets that don't need to be maintained and to draw robot & user traffic to the docs page.
