### ISSUE TITLE
all DevelopmentalStage ontology elements point to the same parents

### ISSUE THREAD

**Issue by jkobject** [laminlabs/bionty#81]
Hello! 

I hope you had a nice weekend, and sorry to come up with yet another question 😅 : 

There seems to be an issue (which I have also seen in some versions of the HsapDV ontology) where all elements of the ontology point to the same parent (the root parent) HsapDv:0000000

However, this is not the case for the version on OLS http://www.ebi.ac.uk/ols4/ontologies/hsapdv/classes?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHsapDv_0000206.

I guess you should be able to get the corrected version there(?)

Best,

**Comment by jkobject** [comment]
Hello @sunnyosun I am reoppening the thread here as we went into a tangent but for the development stage and the tissue ontologies I still see a broken parental tree with the latest version of bionty. Let me know if it has something to do on my end or in the way it has been constructed :) 

Also let me know how I can help, if you tell me where the code is I can try to make PR.

**Comment by sunnyosun** [comment]
@Zethson Could you include `part_of` when parsing parents and update the most recent version of DevelopmentalStage ontologies?

**Comment by Zethson** [comment]
@jkobject thank you for reporting the issue again and offering to help! I'll have a look ASAP. I might use your existing PR (https://github.com/laminlabs/bionty-base/pull/540) as a base and then go from there.

I'll keep you posted...

**Comment by jkobject** [comment]
Hello @Zethson,

Thanks for the help; let me know if you need anything from me or if you have questions about the PR I did. (I might have a look at it as well)
You mentioned an issue with the datafile size if we were to include the part_of relationship. Do you think it will be a problem? (I think only the DevStage and Tissue ontology need to use the part_of relationship)

**Comment by Zethson** [comment]
@jkobject I've updated Bionty to also include other relationships (`part_of`) in this case for DevelopmentalStage and Tissue. With this, I have added new versions of the 2 ontologies that should include the desired relationships.

For you in practice, this means that you can use https://docs.lamin.ai/bionty.core.biorecord#bionty.core.BioRecord.import_from_source to get the latest versions into your lamin instance.

Assuming that you have loaded your instance, it should look something along the lines of:

```
import bionty as bt

new_human_ds = bt.Source.filter(entity="bionty.DevelopmentalStage", organism="human", version="2024-05-28").one()
new_mouse_ds = bt.Source.filter(entity="bionty.DevelopmentalStage", organism="mouse", version="2024-05-28").one()

bt.DevelopmentalStage.import_from_source(new_human_ds)
bt.DevelopmentalStage.import_from_source(new_mouse_ds)

new_tissue = bt.Source.filter(entity="bionty.Tissue", version="2024-08-07").one()
bt.Tissue.import_from_source(new_tissue)
```

If you are using standalone bionty (`bionty.base`) you can simply specify the new versions after we have made a new release. Technically you could also adapt your local sources to include the new versions but if it's not urgent, it might be easier to just wait.

The implementation is based on your earlier PR and I added you as a co-author to it. We cannot transfer PRs from archived repositories to this one, sorry.

Please ask away if something is unclear or doesn't work as expected!

**Comment by jkobject** [comment]
Awesome thanks! I will check it as soon as I can.
